### ISSUE TITLE
would it be possible to use a relative URL?   

### ISSUE THREAD

**Issue by yurg** [cfek/advent_calendar#1]
https://github.com/cfek/advent_calendar/blob/da915dab04bc4a2fe109430bfde208f442a91dc8/js/advent_calendar.js#L23

**Comment by cfek** [comment]
As addressed in the README file >
in advent_calendar.js: line 23 should be changed to the generic path to the day nodes in your project, then we add the specific node id with {path} variable

**Comment by cfek** [comment]
Actually updated the line to reflect relative URL, thank you for your feedback!
